server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://1.117.5.70:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 153500552Mysql.com
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 1.117.5.70
    port: 6379
    password:

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:cn/hk/foo/mall/mbg/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间


# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头